#!/usr/bin/env python3
"""
Soulfra Installation Wizard

Interactive setup for deploying Soulfra ghost writing platform.

Handles:
- Dependency installation
- Environment configuration
- Database initialization
- Admin user creation
- License generation
- Domain setup guidance

Usage:
    python3 install.py

Or non-interactive:
    python3 install.py --email admin@myblog.com --domain myblog.com --tier pro --auto
"""

import argparse
import os
import sys
import subprocess
import sqlite3
import secrets
from pathlib import Path
from typing import Dict

# ANSI colors for terminal output
class Colors:
    HEADER = '\033[95m'
    BLUE = '\033[94m'
    GREEN = '\033[92m'
    YELLOW = '\033[93m'
    RED = '\033[91m'
    END = '\033[0m'
    BOLD = '\033[1m'

def print_header(text):
    print(f"\n{Colors.HEADER}{Colors.BOLD}{'='*80}{Colors.END}")
    print(f"{Colors.HEADER}{Colors.BOLD}{text:^80}{Colors.END}")
    print(f"{Colors.HEADER}{Colors.BOLD}{'='*80}{Colors.END}\n")

def print_success(text):
    print(f"{Colors.GREEN}✓ {text}{Colors.END}")

def print_error(text):
    print(f"{Colors.RED}✗ {text}{Colors.END}")

def print_warning(text):
    print(f"{Colors.YELLOW}⚠️  {text}{Colors.END}")

def print_info(text):
    print(f"{Colors.BLUE}ℹ️  {text}{Colors.END}")

def check_python_version() -> bool:
    """Check if Python version is 3.8+"""
    print_header("CHECKING PYTHON VERSION")

    version = sys.version_info
    print(f"Python version: {version.major}.{version.minor}.{version.micro}")

    if version.major < 3 or (version.major == 3 and version.minor < 8):
        print_error(f"Python 3.8+ required. You have {version.major}.{version.minor}")
        return False

    print_success("Python version OK")
    return True

def install_dependencies(auto: bool = False) -> bool:
    """Install required Python packages"""
    print_header("INSTALLING DEPENDENCIES")

    requirements_file = Path('requirements.txt')

    if not requirements_file.exists():
        print_warning("requirements.txt not found. Creating basic requirements...")

        basic_requirements = """flask>=2.0.0
markdown2>=2.4.0
pandas>=1.3.0
openpyxl>=3.0.0
scikit-learn>=1.0.0
"""
        requirements_file.write_text(basic_requirements)

    if not auto:
        response = input("Install dependencies from requirements.txt? (y/n): ")
        if response.lower() != 'y':
            print_warning("Skipping dependency installation")
            return True

    try:
        print("Running: pip install -r requirements.txt")
        subprocess.run([sys.executable, '-m', 'pip', 'install', '-r', 'requirements.txt'],
                      check=True, capture_output=False)
        print_success("Dependencies installed")
        return True
    except subprocess.CalledProcessError as e:
        print_error(f"Failed to install dependencies: {e}")
        return False

def setup_environment(config: Dict) -> bool:
    """Create .env file with configuration"""
    print_header("SETTING UP ENVIRONMENT")

    env_file = Path('.env')

    # Generate secrets
    secret_key = secrets.token_urlsafe(32)
    admin_password = secrets.token_urlsafe(16)

    env_content = f"""# Soulfra Configuration
# Generated by install.py on {config['timestamp']}

# Platform
PLATFORM_VERSION=1.0.0
BASE_URL={config['base_url']}

# Security
SECRET_KEY={secret_key}
ADMIN_PASSWORD={admin_password}

# Database
DATABASE_PATH=soulfra.db
DATABASE_VERSION=2

# AI/Ollama (optional)
OLLAMA_HOST=http://localhost:11434
ENABLE_AI_REASONING=true

# Email (optional - configure later)
SMTP_HOST=smtp.gmail.com
SMTP_PORT=587
SMTP_EMAIL=
SMTP_PASSWORD=

# Claude API (optional - configure later)
CLAUDE_API_KEY=

# Features
ENABLE_ML=true
ENABLE_QR_TRACKING=true
ENABLE_SEARCH=true
"""

    env_file.write_text(env_content)

    print_success(f"Environment file created: {env_file}")
    print_info(f"Admin password: {admin_password}")
    print_warning("Save this password! It's in .env file")

    return True

def initialize_database() -> bool:
    """Initialize SQLite database with schema"""
    print_header("INITIALIZING DATABASE")

    try:
        # Import database init function
        from database import init_db
        init_db()
        print_success("Database initialized")

        # Initialize license tables
        from license_manager import init_license_tables
        init_license_tables()
        print_success("License tables created")

        return True
    except ImportError as e:
        print_error(f"Cannot import database module: {e}")
        print_info("Make sure database.py exists")
        return False
    except Exception as e:
        print_error(f"Database initialization failed: {e}")
        return False

def create_admin_user(email: str) -> bool:
    """Create admin user in database"""
    print_header("CREATING ADMIN USER")

    try:
        conn = sqlite3.connect('soulfra.db')
        cursor = conn.cursor()

        # Check if users table exists
        cursor.execute("SELECT name FROM sqlite_master WHERE type='table' AND name='users'")
        if not cursor.fetchone():
            print_warning("Users table doesn't exist. Skipping admin user creation.")
            conn.close()
            return True

        # Check if admin already exists
        cursor.execute("SELECT id FROM users WHERE email = ?", (email,))
        if cursor.fetchone():
            print_warning(f"Admin user already exists: {email}")
            conn.close()
            return True

        # Create admin user
        cursor.execute("""
            INSERT INTO users (username, email, is_admin)
            VALUES (?, ?, ?)
        """, ('admin', email, 1))

        conn.commit()
        conn.close()

        print_success(f"Admin user created: {email}")
        return True

    except Exception as e:
        print_error(f"Failed to create admin user: {e}")
        return False

def generate_license(email: str, tier: str) -> bool:
    """Generate license and API key for user"""
    print_header("GENERATING LICENSE")

    try:
        from license_manager import create_license, create_api_key

        # Create license
        license_key, license_id = create_license(email, tier)

        if license_id:
            # Generate API key
            api_key = create_api_key(license_key, name="Default")

            print_success("License generated successfully")
            print_info(f"Save your license key: {license_key}")
            print_info(f"Save your API key: {api_key}")

            # Save to file for reference
            credentials_file = Path('CREDENTIALS.txt')
            credentials_content = f"""Soulfra Credentials
Generated: {config['timestamp']}

Email: {email}
Tier: {tier}

License Key: {license_key}
API Key: {api_key}

Admin Password: (see .env file)

⚠️  KEEP THIS FILE SECURE! Delete after saving credentials to password manager.
"""
            credentials_file.write_text(credentials_content)
            print_success(f"Credentials saved to: {credentials_file}")

        return True

    except Exception as e:
        print_error(f"Failed to generate license: {e}")
        return False

def print_next_steps(config: Dict):
    """Print next steps after installation"""
    print_header("INSTALLATION COMPLETE!")

    print(f"""{Colors.GREEN}
🎉 Soulfra is installed and ready to use!
{Colors.END}
{Colors.BOLD}Next Steps:{Colors.END}

1. Start the server:
   {Colors.BLUE}python3 app.py{Colors.END}

   Or with gunicorn (production):
   {Colors.BLUE}pip install gunicorn{Colors.END}
   {Colors.BLUE}gunicorn -w 4 -b 0.0.0.0:5001 app:app{Colors.END}

2. Visit your blog:
   {Colors.BLUE}{config['base_url']}{Colors.END}

3. Configure your domain (if using custom domain):
   {Colors.BLUE}python3 dns_setup_guide.py --domain {config.get('domain', 'yourdomain.com')} --ip YOUR_IP{Colors.END}

4. Import existing posts (optional):
   {Colors.BLUE}python3 batch_import_posts.py --file your_posts.csv --import{Colors.END}

5. Generate content with Claude AI (optional):
   - Add CLAUDE_API_KEY to .env file
   {Colors.BLUE}python3 force_claude_write.py --brand yourbrand --topic "topic" --save{Colors.END}

6. Check out the documentation:
   - QUICKSTART.md - Quick start guide
   - ARCHITECTURE_EXPLAINED.md - How it all works
   - DEPLOYMENT.md - Production deployment

{Colors.BOLD}Important Files:{Colors.END}
   - .env - Configuration (keep secret!)
   - CREDENTIALS.txt - License & API keys (keep secret!)
   - soulfra.db - Your database

{Colors.BOLD}Need Help?{Colors.END}
   - Documentation: https://docs.soulfra.com
   - Issues: https://github.com/calriven/soulfra/issues
   - Email: support@soulfra.com

{Colors.GREEN}Happy writing! 🚀{Colors.END}
""")

def interactive_setup() -> Dict:
    """Interactive setup wizard"""
    print_header("SOULFRA INSTALLATION WIZARD")

    print("""
Welcome to Soulfra - The AI-powered ghost writing platform!

This wizard will help you set up:
- Python dependencies
- Database
- Admin account
- License & API keys
- Domain configuration (optional)

Let's get started!
""")

    config = {}

    # Email
    config['email'] = input("📧 Admin email address: ").strip()
    if not config['email'] or '@' not in config['email']:
        print_error("Invalid email address")
        return None

    # Domain
    domain_choice = input("\n🌐 Do you have a custom domain? (y/n): ").strip().lower()
    if domain_choice == 'y':
        config['domain'] = input("   Domain (e.g., myblog.com): ").strip().lower()
        config['base_url'] = f"https://{config['domain']}"
    else:
        config['domain'] = None
        config['base_url'] = "http://localhost:5001"

    # Tier
    print(f"\n{Colors.BOLD}Choose your tier:{Colors.END}")
    print("1. Free - 100 posts/month, 1 brand")
    print("2. Pro - Unlimited posts, 5 brands, API access ($15/year)")
    print("3. Enterprise - Unlimited everything (custom pricing)")

    tier_choice = input("\nTier (1/2/3): ").strip()
    tier_map = {'1': 'free', '2': 'pro', '3': 'enterprise'}
    config['tier'] = tier_map.get(tier_choice, 'free')

    # Timestamp
    from datetime import datetime
    config['timestamp'] = datetime.now().isoformat()

    return config

def main():
    parser = argparse.ArgumentParser(description="Soulfra Installation Wizard")
    parser.add_argument('--email', help='Admin email address')
    parser.add_argument('--domain', help='Custom domain (e.g., myblog.com)')
    parser.add_argument('--tier', choices=['free', 'pro', 'enterprise'], default='free', help='License tier')
    parser.add_argument('--auto', action='store_true', help='Non-interactive mode (use with --email)')

    args = parser.parse_args()

    # Check Python version first
    if not check_python_version():
        return 1

    # Get configuration
    global config
    if args.auto and args.email:
        # Non-interactive mode
        from datetime import datetime
        config = {
            'email': args.email,
            'domain': args.domain,
            'base_url': f"https://{args.domain}" if args.domain else "http://localhost:5001",
            'tier': args.tier,
            'timestamp': datetime.now().isoformat()
        }
    else:
        # Interactive mode
        config = interactive_setup()
        if not config:
            return 1

    # Run installation steps
    steps = [
        ("Install dependencies", lambda: install_dependencies(args.auto)),
        ("Setup environment", lambda: setup_environment(config)),
        ("Initialize database", lambda: initialize_database()),
        ("Create admin user", lambda: create_admin_user(config['email'])),
        ("Generate license", lambda: generate_license(config['email'], config['tier']))
    ]

    for step_name, step_func in steps:
        if not step_func():
            print_error(f"Installation failed at: {step_name}")
            return 1

    # Print next steps
    print_next_steps(config)

    return 0

if __name__ == "__main__":
    sys.exit(main())
